name: ASMR Video Automation

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours
  workflow_dispatch:

jobs:
  run-asmr-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 🧱 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick

      - name: 🧪 Install Python packages
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: ▶️ Run ASMR Bot
        run: python asmr-automation-agent.py
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RUN_ONCE: "true"

      - name: 📤 Upload logs and media
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: asmr-logs
          path: |
            *.log
            *.txt
            *.mp4
            *.mp3
            *.wav
